import type { BuilderCapabilityGroup, BuilderCapabilityMeta, BuilderTabType } from './builderTabs.types'

export const BUILDER_TAB_REGISTRY: Record<BuilderTabType, BuilderCapabilityMeta> = {
  preview: {
    type: 'preview',
    title: '预览',
    description: '实时预览云端沙箱构建产物',
    icon: 'monitor',
    group: 'build_preview',
    tier: 'P0',
    enabled: true,
    singleton: true,
    defaultClosable: false,
  },
  new_tab: {
    type: 'new_tab',
    title: '新标签页',
    description: '从能力卡片中打开新的云端页面',
    icon: 'plus',
    group: 'build_preview',
    tier: 'P0',
    enabled: true,
    singleton: true,
    defaultClosable: true,
  },
  agent_config: {
    type: 'agent_config',
    title: '智能体配置',
    description: '配置人设、模型、提示词和能力边界',
    icon: 'bot',
    group: 'build_preview',
    tier: 'P0',
    enabled: true,
    singleton: true,
    defaultClosable: true,
  },
  skills: {
    type: 'skills',
    title: '技能',
    description: '选择和配置 Agent 可调用的工具与技能',
    icon: 'wrench',
    group: 'build_preview',
    tier: 'P0',
    enabled: true,
    singleton: true,
    defaultClosable: true,
  },
  knowledge: {
    type: 'knowledge',
    title: '知识库',
    description: '上传与管理 Agent 可检索的知识',
    icon: 'book',
    group: 'build_preview',
    tier: 'P0',
    enabled: true,
    singleton: true,
    defaultClosable: true,
  },
  run_logs: {
    type: 'run_logs',
    title: '运行日志',
    description: '查看调用链路、错误和 Token 消耗',
    icon: 'scroll',
    group: 'release_ops',
    tier: 'P0',
    enabled: true,
    singleton: true,
    defaultClosable: true,
  },
  deploy: {
    type: 'deploy',
    title: '部署',
    description: '发布链接并查看部署状态',
    icon: 'rocket',
    group: 'release_ops',
    tier: 'P0',
    enabled: true,
    singleton: true,
    defaultClosable: true,
  },
  connector: {
    type: 'connector',
    title: '集成管理',
    description: '配置外部 API、Webhook 与第三方服务',
    icon: 'plug',
    group: 'integration',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  env_vars: {
    type: 'env_vars',
    title: '环境变量',
    description: '安全存储 API Key 与运行配置',
    icon: 'key',
    group: 'integration',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  database: {
    type: 'database',
    title: '数据库',
    description: '管理项目结构化数据',
    icon: 'database',
    group: 'integration',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  object_storage: {
    type: 'object_storage',
    title: '对象存储',
    description: '管理图片、视频、文档等资源',
    icon: 'folder',
    group: 'integration',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  versions: {
    type: 'versions',
    title: '版本历史',
    description: '查看构建记录、发布版本与回滚点',
    icon: 'history',
    group: 'release_ops',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  analytics: {
    type: 'analytics',
    title: '数据分析',
    description: '查看调用量、成功率与活跃用户',
    icon: 'chart',
    group: 'release_ops',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  workflow: {
    type: 'workflow',
    title: '工作流',
    description: '轻量工作流编排与流程编排能力',
    icon: 'workflow',
    group: 'release_ops',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  cloud_terminal: {
    type: 'cloud_terminal',
    title: '云端沙箱终端',
    description: '在云端隔离环境中运行调试命令',
    icon: 'terminal',
    group: 'dev_tools',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  cloud_editor: {
    type: 'cloud_editor',
    title: '云端沙箱文件编辑器',
    description: '编辑云端沙箱文件，不访问本地文件系统',
    icon: 'file',
    group: 'dev_tools',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  version_control: {
    type: 'version_control',
    title: '版本控制',
    description: '管理云端构建版本与变更',
    icon: 'git',
    group: 'dev_tools',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
  debug_console: {
    type: 'debug_console',
    title: '调试控制台',
    description: '查看云端运行调试输出与系统事件',
    icon: 'bug',
    group: 'dev_tools',
    tier: 'P1',
    enabled: false,
    singleton: true,
    defaultClosable: true,
  },
}

export const NEW_TAB_GROUP_LABELS: Record<BuilderCapabilityGroup, string> = {
  build_preview: '构建与预览',
  integration: '集成服务',
  release_ops: '发布与运营',
  dev_tools: '开发工具（默认折叠）',
}

export const NEW_TAB_GROUP_ORDER: BuilderCapabilityGroup[] = ['build_preview', 'integration', 'release_ops', 'dev_tools']

export function getCapabilityMeta(type: BuilderTabType) {
  return BUILDER_TAB_REGISTRY[type]
}
